version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: singularo/s2i-shepherd-drupal-dev:8.1
    hostname: ${PROJECT}.${DOMAIN:-127.0.0.1.nip.io}
    environment:
      CONFIG_SYNC_DIR: ../config/sync
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      HASH_SALT: random-hash
      MEMCACHE_ENABLED: 0
      MEMCACHE_HOST: memcached
      PHP_IDE_CONFIG: serverName=${PROJECT}.${DOMAIN:-127.0.0.1.nip.io}
      PUBLIC_DIR: /shared/public
      SHEPHERD_ENVIRONMENT: local
      SHEPHERD_SECRET_PATH: /code/private
      SITE_TITLE: Drupal site
      SITE_MAIL: site@example.com
      SITE_ADMIN_EMAIL: admin@example.com
      SITE_ADMIN_USERNAME: admin
      SITE_ADMIN_PASSWORD: password
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
      TMP_DIR: /shared/tmp

      SIMPLETEST_BASE_URL: http://${PROJECT}.${DOMAIN:-127.0.0.1.nip.io}:8080
      DTT_BASE_URL: http://${PROJECT}.${DOMAIN:-127.0.0.1.nip.io}:8080

      # Use jwilder/nginx-proxy for virtual hosts.
      VIRTUAL_HOST: ${PROJECT}.${DOMAIN:-127.0.0.1.nip.io}
      # Do not define this as '/' or apache2 will give strange behaviour, to test locally,
      # change to the web directory and create a symlink to the subpath name eg ln -s . subpath
      # WEB_PATH: /subpath

      XDEBUG_CONFIG: "remote_host=host.docker.internal discover_client_host=1 client_host=host.docker.internal"
      XDEBUG_MODE: debug,develop
      XDEBUG_SESSION: 1
    env_file:
      - .env
    volumes:
      - .:/code
      - ./shared:/shared
      - ./shared/public:/code/web/sites/default/files
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    networks:
      - default

  db:
    image: mariadb
    #ports:
    #  - "33062:3306"
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: super-secret-password
    networks:
      - default

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_HOST: mail.${PROJECT}.${DOMAIN:-127.0.0.1.nip.io}
      VIRTUAL_PORT: 8025
    networks:
      - default

  memcached:
    image: memcached:alpine
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome:106.0
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - default
